Implemented review comments.
Also fixed various bugs similar to the following where the second `Project.compile` call, c.f. #483, caused the EPUB file to be written again and the EPUB checker at the same time trying to access the file causing it to fail:

    Error: 1: Error: Command failed: ERROR: /tmp/scripler/app/users/user548814ca484b378427b5e237/548814e0484b378427b5e47a.epub: I/O error: error in opening zip file Check finished with warnings or errors at ChildProcess.exithandler (child_process.js:648:15) at ChildProcess.emit (events.js:98:17) at maybeClose (child_process.js:756:16) at Socket. (child_process.js:969:11) at Socket.emit (events.js:95:17) at Pipe.close (net.js:465:12)