Run EPUB validator from IT. This reported the errors below which have been fixed.
```
C:\Users\mgf\Dropbox\Dokumenter\Udvikling\Kode\Scripler\Github\Scripler\scripler>java
-jar test\epubcheck-3.0b5.jar 52c048c0818f03f020000005.epub
Epubcheck Version 3.0b5

Validating against EPUB version 2.0
ERROR: 52c048c0818f03f020000005.epub/OEBPS/content.opf(8,62): date value
'1388333248564' is not valid as per
http://www.w3.org/TR/NOTE-datetime:[For input string: "1388333248564"] is
not an integer
ERROR: 52c048c0818f03f020000005.epub/OEBPS/content.opf(22,117): value of
attribute "id" is invalid; must be an XML name without colons
ERROR: 52c048c0818f03f020000005.epub/OEBPS/content.opf(34,46): value of
attribute "idref" is invalid; must be an XML name without colons
ERROR: 52c048c0818f03f020000005.epub/OEBPS/content.opf(22,117): assertion
failed: The "id" attribute does not have a unique value
ERROR: 52c048c0818f03f020000005.epub/OEBPS/content.opf(39,63): File listed
in reference element in guide was not declared in OPF manifest:
OEBPS/Cover.html
ERROR: 52c048c0818f03f020000005.epub/OEBPS/content.opf(28,118):
non-standard media-type 'application/x-font-ttf' with no fallback
ERROR: 52c048c0818f03f020000005.epub: OPS/XHTML file
OEBPS/HTML/52c048c0818f03f02000000b.html is missing
ERROR: 52c048c0818f03f020000005.epub: image file
OEBPS/Images/52c048c0818f03f02000000b.jpg is missing
ERROR: 52c048c0818f03f020000005.epub: resource
OEBPS/Fonts/52c048c0818f03f02000000b.tff is missing
ERROR: 52c048c0818f03f020000005.epub: resource OEBPS/Scripler-license.txt
is missing
WARNING: 52c048c0818f03f020000005.epub: item (OEBPS/HTML/A New Cool
Name.html) exists in the zip file, but is not declared in the OPF file
WARNING: 52c048c0818f03f020000005.epub/OEBPS/HTML/A New Cool Name.html:
Filename contains spaces. Consider changing filename such that URI
escaping is not necessary
ERROR: 52c048c0818f03f020000005.epub/OEBPS/content.opf(39,63):
'OEBPS/Cover.html': referenced resource missing in the package

Check finished with warnings or errors
```

Also:

* Send real XML (HTML) such to pass EPUB validation.
* Implemented Allan's review comments, except for comment about multiple authors which might require a) discussion with product owner (David) or b) rewriting the code to generate XML/HTML via a library.
* Changed ITs that open folders to not test exact returned index of documents and folders, since this is currently not guaranteed by the server (Folder.Open()).